Topics:
  fcconnect:
    - request
    - response
  fcdisconnect:
    - request
    - response  
  discovery:
    - request
    - response
  telemetry:
    - update
  command:
    - takeoff
    - land
    - goto
  video:
    - start
    - stop
  heartbeat:
    - edge
    - ground
  mission_upload:
    - request
    - response  